sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
    
language: r
r: bioc-release
pandoc_version: 1.19.2.1

r_github_packages: compgenomr/compGenomRData

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy_github.sh

script:
  - ./_build.sh
  - ./_deploy_github.sh
  
